TEST_SAMPLES: list[tuple[str, str]] = [
    ("这个多少钱", "price"),
    ("能便宜点吗", "price"),
    ("还能再少点吗", "price"),
    ("打折吗", "price"),
    ("最低多少钱", "price"),
    ("我要退货", "after_sale"),
    ("退款怎么操作", "after_sale"),
    ("换货流程是什么", "after_sale"),
    ("发错货了", "after_sale"),
    ("东西坏了", "after_sale"),
    ("我要投诉", "complaint"),
    ("投诉你们客服", "complaint"),
    ("你们什么服务态度", "complaint"),
    ("转人工", "handover"),
    ("找人工客服", "handover"),
    ("这个参数是多少", "tech"),
    ("内存多大", "tech"),
    ("兼容Windows吗", "tech"),
    ("怎么安装", "tech"),
    ("你好", "default"),
    ("在吗", "default"),
    ("谢谢", "default"),
]
